ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autoupdate_schedule: weekly
  autofix_commit_msg: "style: pre-commit fixes"

repos:
  ## Ruff check & fix
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.278
    hooks:
      - id: ruff
        ## , --exit-non-zero-on-fix
        args: [--fix, --config, ruff.ci.toml]
        ## Run on notebooks too
        types_or: [python, pyi, jupyter]

  - repo: local
    hooks:
      - id: nox-lint
        name: nox-lint
        entry: nox -s lint --
        language: system
        types: [python]
        require_serial: true
