[project]
name = "std-context-managers"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "red-utils-core",
]

# [project.scripts]
# hello = "std_context_managers:hello"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

## Fix ValueError about hatch being unable to determine which files to ship inside the wheel.
[tool.hatch.build.targets.wheel]
packages = ["red_utils.std.context_managers"]

[tool.uv.sources]
red-utils-core = { workspace = true }
