[project]
name = "ext-httpx-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    # "core",
    "dynaconf>=3.2.6",
    "hishel>=0.0.33",
    "httpx>=0.27.2"
]

# [project.scripts]
# hello = "ext_httpx_utils:hello"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

## Fix ValueError about hatch being unable to determine which files to ship inside the wheel.
[tool.hatch.build.targets.wheel]
packages = ["src/red_utils"]

[tool.uv.sources]
red-utils-core = { workspace = true }

# [tool.uv.sources]
# core = { workspace = true }
