---
name: Export project requirements.txt file(s)


on:
  pull_request:
    branches:
      # - main
      # - dev
      - workflow-test

jobs:
  export-requirements:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          run: |
            git config user.name "GitHub Action"
            git config user.email "action@github.com"

      # - name: Fetch code
      #   run: git fetch origin pull/${{ github.event.pull_request.number }}/head:pr_branch

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install PDM
        run: |
          python -m pip install pdm
          pdm --version

      - name: Export requirements.txt
        run: |
          pdm export --prod -o requirements.txt --without-hashes
          cat requirements.txt

      - name: Export requirements.dev.txt
        run: |
          pdm export -d -o requirements.dev.txt --without-hashes
          cat requirements.dev.txt

      - name: Commit & push changes
        # git config --global user.email "actions@github.com"
        # git config --global user.name "Github Actions"
        run: |
          git add requirements.txt requirements.dev.txt
          git commit -m "Auto-export requirements files"
          git push
