---
name: Export project requirements.txt file(s)

on:
  pull_request:
    branches:
      - main
      - dev
      - ci

jobs:
  export-requirements:
    runs-on: ubuntu-latest

    matrix:
      python-major-version: [3]
      python-minor-version: [11, 12]

    env:
      python-version: ${{ format('{0}.{1}', matrix.python-major-version, matrix.python-minor-version)}}

    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python-version }}

      - name: Install nox
        run: |
          python -m pip install nox
          nox --version
      
      - name: Create nox testenv
        run: nox -s testenv --no-error-on-missing-interpreters

      - name: Export requirements
        run: nox -s export --no-error-on-missing-interpreters

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.11

      # - name: Install PDM
      #   run: |
      #     python -m pip install pdm
      #     pdm --version

      # - name: Export requirements.txt
      #   run: |
      #     pdm export --prod -o requirements.txt --without-hashes
      #     cat requirements.txt

      # - name: Export requirements.dev.txt
      #   run: |
      #     pdm export -d -o requirements.dev.txt --without-hashes
      #     cat requirements.dev.txt

      # - name: Export requirements.ci.txt
      #   run: |
      #     pdm export -d -o requirements.ci.txt --without-hashes
      #     cat requirements.ci.txt

      # - name: Commit & push changes
      #   run: |
      #     git config user.name "GitHub Action"
      #     git config user.email "action@github.com"

      #     ## If there are no changes, this keeps the workflow from failing
      #     if [[ -n $(git status -s) ]]; then
      #       git add requirements.txt requirements.dev.txt requirements.ci.txt
      #       git commit -m "Auto-export requirements files"
      #       git push
      #     else
      #       echo "No changes to commit."
      #     fi
