---
name: Export project requirements.txt file(s)

on:
  # push:
  #   branches:
  #     - dev
  #     - ci
  pull_request:
    branches:
      - main
      - dev
      - ci

jobs:
  export-requirements:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install PDM
        run: |
          python -m pip install pdm
          pdm --version

      - name: Export requirements.txt
        run: |
          pdm export --prod -o requirements.txt --without-hashes
          cat requirements.txt

      - name: Export requirements.dev.txt
        run: |
          pdm export -d -o requirements.dev.txt --without-hashes
          cat requirements.dev.txt

      - name: Export requirements.ci.txt
        run: |
          pdm export -d -o requirements.ci.txt --without-hashes
          cat requirements.ci.txt

      - name: Commit & push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

          ## If there are no changes, this keeps the workflow from failing
          if [[ -n $(git status -s) ]]; then
            git add requirements.txt requirements.dev.txt requirements.ci.txt
            git commit -m "Auto-export requirements files"
            git push
          else
            echo "No changes to commit."
          fi
