---
name: Lint & format code

on:
  pull_request:
    branches:
      - main
      - dev
      - ci

jobs:

  export-requirements:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.12'
          - '3.11'

    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
        needs: build

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version:
            - 3.11

      - name: Install nox
        run: |
          python -m pip install nox pdm
          pdm --version
          nox --version

      - name: Create nox testenv
        run: nox -s testenv --no-error-on-missing-interpreters

      - name: Lint & format
        run: nox -s lint --no-error-on-missing-interpreters

      - name: Commit & push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

          ## If there are no changes, this keeps the workflow from failing
          if [[ -n $(git status -s) ]]; then
            git add requirements.txt requirements.dev.txt requirements.ci.txt
            git commit -m "Auto-export requirements files"
            git push
          else
            echo "No changes to commit."
          fi
