---
name: Lint & format code

on:
  pull_request:
    branches:
      - main
      - dev
      - ci

jobs:
  export-requirements:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: fjwillemsen/setup-nox2@v3.0.0

      - name: Create nox testenv
        run: nox -s testenv

      - name: Lint & format
        run: nox -s lint
