---
name: Lint & format code

on:
  pull_request:
    branches:
      - main
      - dev
      - ci

jobs:

  matrix:
    python-major-version: [3]
    python-minor-version: [11, 12]

  env:
    python-version: ${{ format('{0}.{1}', matrix.python-major-version, matrix.python-minor-version)}}

  export-requirements:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      # - uses: fjwillemsen/setup-nox2@v3.0.0

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python-version }}

      - name: Install nox
        run: |
          python -m pip install nox
          nox --version

      - name: Create nox testenv
        run: nox -s testenv --no-error-on-missing-interpreters

      - name: Lint & format
        run: nox -s lint --no-error-on-missing-interpreters
