---
name: Lint & format code

on:
  pull_request:
    branches:
      - main
      - dev
      - ci
    # Do not trigger tests for documentation or markdown docs.
    paths-ignore:
      - "docs/**"
      - "*.md"

jobs:
  lint-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
        if: ${{ matrix.python-version == '3.11' }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install nox
        run: |
          python -m pip install nox pdm
          pdm --version
          nox --version
        if: ${{ matrix.python-version == '3.11' }}

      - name: Lint & format
        run: python -m nox -s lint
        if: ${{ matrix.python-version == '3.11' }}

      - name: Commit & push changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git config advice.addIgnoredFile false

          ## If there are no changes, this keeps the workflow from failing
          if [[ -n $(git status -s) ]]; then
            git add .
            git commit -m "Lint & format"
            git push
          else
            echo "No changes to commit."
          fi
        if: ${{ matrix.python-version == '3.11' }}
