---
name: Lint & format code

on:
  pull_request:
    branches:
      - main
      - dev
      - ci

jobs:

  export-requirements:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.12'
          - '3.11'

    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      # - uses: fjwillemsen/setup-nox2@v3.0.0

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install nox
        run: |
          python -m pip install nox
          nox --version

      - name: Create nox testenv
        run: nox -s testenv --no-error-on-missing-interpreters

      - name: Lint & format
        run: nox -s lint --no-error-on-missing-interpreters
