---
name: Lint & format code

on:
  pull_request:
    branches:
      - main
      - dev
      - ci

jobs:
  export-requirements:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        uses: daisylb/setup-nox@v2.1.0
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Lint & format
        run: nox -s lint
