## Get tag version with:
#  ${{ github.event.release.tag_name }}

name: Build, tag, and release

on:
  pull_request:
    branches:
      - release
    # tags:
    #   - "v*"

jobs:
  ## Format stage runs linters/checkers
  format:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      ## Install PDM in the pipeline
      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          # Version range or exact version of a Python version to use, the same as actions/setup-python
          python-version: ${{ matrix.python-version }}
          cache: true
          # https://github.com/marketplace/actions/setup-pdm#caches
          cache-dependency-path: |
            ./pdm.lock
          # The target architecture (x86, x64) of the Python interpreter. the same as actions/setup-python
          architecture: x64
          # The version of PDM to install. Leave it as empty to use the latest version from PyPI, or 'head' to use the latest version from GitHub
          # version:
          # Allow prerelease versions of PDM to be installed
          prerelease: false
          # Enable PEP 582 package loading globally
          enable-pep582: false
          # Allow prerelease versions of Python to be installed. For example if only 3.12-dev is available, 3.12 will fallback to 3.12-dev
          allow-python-prereleases: false

      - name: Install dependencies
        run: pdm sync

      - name: Lint with Ruff
        ## Custom script in pyproject.toml
        run: pdm run format

  build:
    ## Build a release, create a tag, bump pyproject.toml, push tag
    needs: format
    if: ${{ github.event_name == 'push' }}
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: read
    strategy:
      matrix:
        python-version: ["3.11"]
        ## , macOS-latest, windows-latest
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      ## Install PDM in the pipeline
      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          # Version range or exact version of a Python version to use, the same as actions/setup-python
          python-version: ${{ matrix.python-version }}
          cache: true
          # https://github.com/marketplace/actions/setup-pdm#caches
          # cache-dependency-path: |
          #   ./pdm.lock
          # The target architecture (x86, x64) of the Python interpreter. the same as actions/setup-python
          architecture: x64
          # The version of PDM to install. Leave it as empty to use the latest version from PyPI, or 'head' to use the latest version from GitHub
          # version:
          # Allow prerelease versions of PDM to be installed
          prerelease: false
          # Enable PEP 582 package loading globally
          enable-pep582: false
          # Allow prerelease versions of Python to be installed. For example if only 3.12-dev is available, 3.12 will fallback to 3.12-dev
          allow-python-prereleases: false

      - name: Install dependencies
        run: pdm install

      ## Add pdm-bump plugin
      - name: Add pdm-bump
        run: |
          pdm self add pdm-bump

      ## Build app inside pipeline
      - name: Build app
        run: pdm build

      ## Bump the pyproject version (micro is 0.0.x <--)
      - name: Bump pyproject version
        run: |
          pdm bump micro

      ## Create a tag from version bump
      - name: Bump tag
        run: |
          pdm bump tag

      ## This is supposed to get the most recent tag, but it doesn't
      #  and I don't want to spend any more time trying to get this to work.
      - name: Get branch name for commit
        id: tag_version
        run: |
          echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      ## Push tag to repo
      - name: Push tag
        run: |
          git config user.name "github-action[bot]"
          git config user.email "github-action[bot]@no-reply.github.com"
          git add pyproject.toml
          git commit -m "Bump version from ${{ steps.tag_version.outputs.TAG }}"
          git push
          git push --tags

  release:
    ## Create a release from most recent build tag
    needs: build
    if: ${{ github.event_name == 'push' }}
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: read
    strategy:
      matrix:
        python-version: ["3.11"]
        ## , macOS-latest, windows-latest
        os: [ubuntu-latest]

    steps:
      - name: Checkout again before building release
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create release
        uses: konfer-be/action-create-release-from-tag@v1.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
