---
name: Run lint & format PDM Scripts

on:
  push:
    branches:
      - main
      - dev
      - ci

jobs:
  run-pdm-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install PDM & dependencies
        run: |
          python -m pip install pdm
          pdm install -d --no-lock
          pdm --version

      - name: Run PDM Scripts
        run: |
          pdm run ruff check . --fix --config ruff.ci.toml
