---
name: Run Pytest tests

env:
  CI: true

on:
  pull_request:
    branches:
      - main
      - dev
      - ci

jobs:
  run-pytest-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.12'
          - '3.11'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install nox
        run: |
          python -m pip install nox pdm
          pdm --version
          nox --version
      
      - name: Run nox tests
        run: python -m nox -s tests
